### ISSUE TITLE
Please help

### ISSUE THREAD

**Issue by hanwtn** [Kneckter/DiscordRoleBot#10]
The bot crashes everytime it checks the role.

 [InitDB] Failed to execute role check query 1: (TypeError: Cannot read property 'name' of undefined)

How can I fix it?

**Comment by Kneckter** [comment]
Looks like it isn't reading the role's name.

Was the bot working before?
Does the bot have permission to manage roles?
Did you delete the role from the server?
Does the role's ID in the database match the role ID in the server?

**Comment by hanwtn** [comment]
It works fine and crashed after 10 mins(seems crashed at checking roles.) And it registers the role name, not role id. Right?

**Comment by hans334** [comment]
May be I haven't granted privileges? How can I do that in PHPMYADMIN? Sry, I am a newbie.

**Comment by hans334** [comment]
I found out that the bot crashed when the role given user left the server. It is up when the user rejoin. How can i handle this?

**Comment by hanwtn** [comment]
I figured out the problem. I gave temp roles to the user who were already given permanent role by me. I deleted that roles and now it doesn't crash anymore.
But it doesn't remove the role in database on user left. How can I do that?

**Comment by Kneckter** [comment]
I didn't see that you updated your comment to include a question. I made an update to handle people leaving the server differently so I'll push that soon.

**Comment by Kneckter** [comment]
This should be covered with PR #11

**Comment by Anto1337** [comment]
> 
Hi, i have the same error : [InitDB] Failed to execute role check query 1: (TypeError: Cannot read property 'name' of undefined)
how did you fix it pls ?
