### ISSUE TITLE
 [InitDB] Failed to execute role check query 1: (TypeError: Cannot read property 'send' of undefined)

### ISSUE THREAD

**Issue by BUDDGAF** [Kneckter/DiscordRoleBot#12]
Hey there, thanks for the bot it works great but for this one problem which is probably my fault. That's the error it shows in the console. I don't want to use any of the paypal functions of the bot anyway. I have "no" in the config file for donations, paypal, etc. Is there something more I need to do?  also, i should mention that it works fine for for the first 5 minutes or so. I'm able to add/remove/check the timed roles and see those changes reflected in the database. 

Thank you.

**Comment by Kneckter** [comment]
Have you pulled the latest updates? It's either not able to send to `mainChannelID` from your config file or a user left that it cannot DM, which should be handled better with the latest updates.

**Comment by BUDDGAF** [comment]
is `mainChannelID` required? if so, i don't know how i got the idea that it wasn't. let me try setting that.

**Comment by Kneckter** [comment]
Yeah, the bot is trying to post that someone is expiring/expired. So it can give you a heads up.

**Comment by BUDDGAF** [comment]
That did the trick thanks. While I have you here, is there a way for me to add a column to the table the bot uses without messing it up?

**Comment by Kneckter** [comment]
If you know SQL commands, then you can add a column to any of the tables. The bot should be setup to reference all the columns it needs by their names but I haven't tested it with a random column. Just don't make it a required default, allow the default to be null or auto generated.

**Comment by BUDDGAF** [comment]
yeah i just added one at the end, so it would be column 9 and i get [InitDB] Failed to execute query 16: (Error: ER_WRONG_VALUE_COUNT_ON_ROW: Column count doesn't match value count at row 1)

**Comment by Kneckter** [comment]
I thought an `INSERT` would take the default value for the new column, it's coming from these values that don't include the new column: https://github.com/Kneckter/DiscordRoleBot/blob/master/adminBot.js#L480. 

This set would also need an update if you want to add the column to the code: https://github.com/Kneckter/DiscordRoleBot/blob/master/adminBot.js#L1287

**Comment by BUDDGAF** [comment]
thank you!
