### ISSUE TITLE
I couldn't find such role, please check the spelling and try again.

### ISSUE THREAD

**Issue by aliabrar12** [Kneckter/DiscordRoleBot#15]
![image](https://user-images.githubusercontent.com/42883838/144709509-b960ec30-e61b-4812-b077-22de50b3db80.png)

how to fix this ?

**Comment by aliabrar12** [comment]
![image](https://user-images.githubusercontent.com/42883838/144709551-4a7653b7-eda7-4db3-b4d7-dcede67c0f56.png)
i already follow the instruction but still got that notif

**Comment by Kneckter** [comment]
For the add command, it's actually `!tr add @user <ROLE> <DAYS>`. The readme needs to be updated for that

**Comment by aliabrar12** [comment]
okay thanks, and 1 more i cant start pm2 ecosystem.config.js

![image](https://user-images.githubusercontent.com/42883838/144734836-7ab2bf87-3597-4675-84d0-f433b9ee345d.png)

![image](https://user-images.githubusercontent.com/42883838/144734839-9d7f20fb-3df4-44c0-b49b-ce540476c1ca.png)

can you help me with that

**Comment by aliabrar12** [comment]
![image](https://user-images.githubusercontent.com/42883838/144738396-fd0aa77a-d673-4d1b-a460-4f9173b679d0.png)
still can't assign the role to the user I want

**Comment by Kneckter** [comment]
The tr add command is for adding time to an already existing temp role entry. You need to issue the normal temp role command first if they don't have the role yet. so send `!tr @NeoRaizu 2 hari` note that the two commands flip the position or the days/role because it was easier to parse like that
