### ISSUE TITLE
channel spam 

### ISSUE THREAD

**Issue by bibi-blocksberg** [Kneckter/DiscordRoleBot#16]
it wouldn't be enough if he wrote that once and not every 10 minutes 
 
 
 Failed to get user ID: 823939188885815328 <@823939188885815328> from the cache. Tagging them to force the cache update.
[16:40]
 Could not find a user for ID: 823939188885815328 <@823939188885815328>. They may have left the server.
[16:40]
 xences has left the server. All temp role assignments have been marked in the database.
[16:40]
 Failed to get user ID: 852427796332544030 <@852427796332544030> from the cache. Tagging them to force the cache update.
[16:40]
 Could not find a user for ID: 852427796332544030 <@852427796332544030>. They may have left the server.
[16:40]
 MrRespektlos has left the server. All temp role assignments have been marked in the database.
 
 thx for help

**Comment by Kneckter** [comment]
You can pull the latest version and see if that stops the spamming

**Comment by bibi-blocksberg** [comment]
works thanks
