### ISSUE TITLE
Date Format

### ISSUE THREAD

**Issue by BoB3R** [Kneckter/DiscordRoleBot#22]
Hello, would it be possible to add option to change date format for example for dd/mm/yyy etc.?

**Comment by Kneckter** [comment]
Is that related to the date that shows in messages, in logs, or both?

**Comment by BoB3R** [comment]
Hello, in messages. Now it is showing yyy/mm/dd. I've got channel open for user too se how much they got left.
![image](https://user-images.githubusercontent.com/58575145/165458307-524ba6b8-0d3f-493c-a603-06792d2d1861.png)
