### ISSUE TITLE
Can you please add redeem code method?

### ISSUE THREAD

**Issue by ashardaniyal12** [Kneckter/DiscordRoleBot#23]
So first bot creates a key then user will redeem and get the role

**Comment by Kneckter** [comment]
That's not a simple feature. Since the bot has nothing like this, can you give more details about how you see it working? Like what's your trigger for needing a code (on-demand, on-payment, on-join, etc.)? Codes that expire? Codes linked to specific people?

**Comment by Kneckter** [comment]
Closing for lack of feedback.
