### ISSUE TITLE
Bot Crash

### ISSUE THREAD

**Issue by realdocweird** [Kneckter/DiscordRoleBot#7]
`[4/5/2021, 13:07:15] [InitDB] Failed to execute role check query 1: (ReferenceError: err is not defined)` what can cause this?

**Comment by Kneckter** [comment]
If you lookup that message, it's failing during the role check https://github.com/Kneckter/DiscordRoleBot/blob/master/adminBot.js#L128. There are other error catching messages in that block but IDK what it causing yours since the failure didn't report an error. Provide more information like the dependency versions, you are on the latest commit, what has changed since it was working last, do you have data in the DB? Stuff like that

**Comment by realdocweird** [comment]
Looks like it was caused by an user who had a role and left the discord

**Comment by Kneckter** [comment]
Are you on the latest version? There's already code to handle when someone leaves the server while they have a temp role https://github.com/Kneckter/DiscordRoleBot/blob/master/adminBot.js#L629

**Comment by realdocweird** [comment]
yes i'm on last release, and also yes i see the handler but still, i've manually deleted that user and it's not crashing anymore

**Comment by realdocweird** [comment]
```
if(!rows[rowNumber].username && !leftServer) {
                    let name = member.user.username.replace(/[^a-zA-Z0-9]/g, '');
                    await query(`UPDATE temporary_roles SET username="${name}" WHERE userID="${member.id}"`)
                        .catch(err => {
                            console.error(GetTimestamp()+`[InitDB] Failed to execute role check query 4: (${err})`);
                        });
                    console.log(GetTimestamp() + "Updated the username for "+member.id+" to "+name);
                }
```
probably it needs a another handler here if the user has left the server

**Comment by Kneckter** [comment]
The `leftServer` variable is for when they left the server. That check is also just for the username when porting old data from sqlite. Is it possible this person left the server before you updated to the version that tracks member removal or maybe the person left while the bot was offline?

**Comment by realdocweird** [comment]
Nope, i've started everything clean with the last release

**Comment by Kneckter** [comment]
This should be covered with PR #11
